/*
 * This source file was generated by the Gradle 'init' task
 */
package oop.exercise;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void getTicketPrice() {
        App classUnderTest = new App();
        assertEquals(0, classUnderTest.getTicketPrice(1, 2));
    }
}
